version: '3'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
      - "8081:8081"
  client:
    build: ./client
    ports:
      - "3000:3000"
  nginx:
     container_name: goban-nginx
     image: nginx:1.13
     restart: always
     ports:
       - 80:80
     volumes:
       - ./nginx/conf.d:/etc/nginx/conf.d
